name: .NET

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #Set up different caches
    - name: Cache .NET packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~/sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    #Linting code
    ##- name: Lint Code Base
    ##  uses: github/super-linter@v4
    ##  env:
    ##    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #Setting up environment
    #JDK for sonarqube
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install SonarCloud scanner
      working-directory: ./src
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      run: |
        mkdir -p ./.sonar/scanner
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
    - name: Start Sonar
      working-directory: ./src
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./.sonar/scanner/dotnet-sonarscanner begin /k:"papersaltserver_ITLinksBot" /o:"papersaltserver" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.xunit.reportsPaths="./ItLinksBot-Test/test_result.xml" /d:sonar.cs.opencover.reportsPaths="./ItLinksBot-Test/coverage.opencover.xml" /d:sonar.host.url="https://sonarcloud.io"
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore --locked-mode ItLinksBot.sln
    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore ItLinksBot.sln
    - name: Test
      working-directory: ./src
      env:
        TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
        TELEGRAM_CHANNELID: ${{ secrets.TELEGRAM_CHANNELID }}
      run: dotnet test --no-build --verbosity normal --logger:"xunit;LogFilePath=test_result.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ItLinksBot.sln
    - name: Stop Sonar
      working-directory: ./src
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    # This is the a separate action that sets up buildx runner
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # So now you can use Actions' own caching!
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_PASSWORD }}
    # And make it available for the builds
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/ItLinksBot/Dockerfile
        push: true
        tags: papersaltserver/itlinksbot:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_HOST }}
        username: ${{ secrets.OCI_USERNAME }}
        key: ${{ secrets.OCI_KEY }}
        script: |
          sudo /usr/bin/docker pull papersaltserver/itlinksbot:latest
          sudo /usr/bin/docker rm -f oci-linksbot
          sudo /usr/bin/docker run -d --restart unless-stopped -v /home/ubuntu/net5.0/db/:/app/db --env-file /home/ubuntu/net5.0/env.list --name oci-linksbot papersaltserver/itlinksbot:latest
    # This ugly bit is necessary if you don't want your cache to grow forever
    # till it hits GitHub's limit of 5GB.
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
